# Goal: To say Hello in the workflow and tell the title /Name of the repository

# Start with Naming your workflow
name: Hello

# When the workflow runs
on:

  push:
    

#what the workflow does
jobs:

#name of your jobs
  great:
  #where the jobs run OS
    runs-on: ubuntu-latest
    # the sequence of steps the job does
    steps:
      - name: Say Hello
        run: echo "Hello World"

repo-name:
  runs-on: ubuntu-latest
  steps:
    - name: Show repo run-name
      run : exho "The Repo name is hero"
