# Goal: To say Hello in the workflow and tell the title /Name of the repository

# Start with Naming your workflow
name: Hello

# When the workflow runs
on:
  push:

# What the workflow does
jobs:

  # Name of your job
  great:
    # Where the job runs (OS)
    runs-on: ubuntu-latest

    # The sequence of steps the job does
    steps:
      - name: Say Hello
        run: echo "Hello World"

  repo-name:
    needs: great
    runs-on: ubuntu-latest

    steps:
      - name: Show repo run-name
        run: echo "The Repo name is hero"
